// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameRoomPacket
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C2S_EnterGameRoomPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static C2S_EnterGameRoomPacket GetRootAsC2S_EnterGameRoomPacket(ByteBuffer _bb) { return GetRootAsC2S_EnterGameRoomPacket(_bb, new C2S_EnterGameRoomPacket()); }
  public static C2S_EnterGameRoomPacket GetRootAsC2S_EnterGameRoomPacket(ByteBuffer _bb, C2S_EnterGameRoomPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C2S_EnterGameRoomPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short PlayerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  public string PlayerName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPlayerNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetPlayerNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPlayerNameArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<GameRoomPacket.C2S_EnterGameRoomPacket> CreateC2S_EnterGameRoomPacket(FlatBufferBuilder builder,
      short playerId = 0,
      StringOffset playerNameOffset = default(StringOffset)) {
    builder.StartTable(2);
    C2S_EnterGameRoomPacket.AddPlayerName(builder, playerNameOffset);
    C2S_EnterGameRoomPacket.AddPlayerId(builder, playerId);
    return C2S_EnterGameRoomPacket.EndC2S_EnterGameRoomPacket(builder);
  }

  public static void StartC2S_EnterGameRoomPacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPlayerId(FlatBufferBuilder builder, short playerId) { builder.AddShort(0, playerId, 0); }
  public static void AddPlayerName(FlatBufferBuilder builder, StringOffset playerNameOffset) { builder.AddOffset(1, playerNameOffset.Value, 0); }
  public static Offset<GameRoomPacket.C2S_EnterGameRoomPacket> EndC2S_EnterGameRoomPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameRoomPacket.C2S_EnterGameRoomPacket>(o);
  }
}


static public class C2S_EnterGameRoomPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PlayerId*/, 2 /*short*/, 2, false)
      && verifier.VerifyString(tablePos, 6 /*PlayerName*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
