// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameRoomPacket
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RoomPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static RoomPacket GetRootAsRoomPacket(ByteBuffer _bb) { return GetRootAsRoomPacket(_bb, new RoomPacket()); }
  public static RoomPacket GetRootAsRoomPacket(ByteBuffer _bb, RoomPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyRoomPacket(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, RoomPacketVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RoomPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartRoomPacket(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<GameRoomPacket.RoomPacket> EndRoomPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameRoomPacket.RoomPacket>(o);
  }
  public static void FinishRoomPacketBuffer(FlatBufferBuilder builder, Offset<GameRoomPacket.RoomPacket> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedRoomPacketBuffer(FlatBufferBuilder builder, Offset<GameRoomPacket.RoomPacket> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class RoomPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
