// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameRoomPacket
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C2S_MoveInputPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static C2S_MoveInputPacket GetRootAsC2S_MoveInputPacket(ByteBuffer _bb) { return GetRootAsC2S_MoveInputPacket(_bb, new C2S_MoveInputPacket()); }
  public static C2S_MoveInputPacket GetRootAsC2S_MoveInputPacket(ByteBuffer _bb, C2S_MoveInputPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C2S_MoveInputPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Velocity { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public GameRoomPacket.Vector2? Position { get { int o = __p.__offset(6); return o != 0 ? (GameRoomPacket.Vector2?)(new GameRoomPacket.Vector2()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartC2S_MoveInputPacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddVelocity(FlatBufferBuilder builder, float velocity) { builder.AddFloat(0, velocity, 0.0f); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<GameRoomPacket.Vector2> positionOffset) { builder.AddStruct(1, positionOffset.Value, 0); }
  public static Offset<GameRoomPacket.C2S_MoveInputPacket> EndC2S_MoveInputPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameRoomPacket.C2S_MoveInputPacket>(o);
  }
}


static public class C2S_MoveInputPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Velocity*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Position*/, 8 /*GameRoomPacket.Vector2*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
